import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';

// 串行构建五个独立镜头。所有状态均为功能示意，不是实际任务结果。
const font = '@font-face{font-family:"Noto Sans SC";src:url("assets/noto-sans-sc.woff2") format("woff2");font-weight:100 900;font-display:block}';
const css = `${font}
*{box-sizing:border-box} .stage{position:relative;width:100%;height:100%;overflow:hidden;background:#fdfae7;color:#111111;font-family:"Noto Sans SC",sans-serif}
.ground{position:absolute;inset:0;background:#fdfae7}.sheet{font-family:"Noto Sans SC",sans-serif;position:absolute;inset:0;padding:90px 110px}
.brand{font-size:28px;font-weight:650;letter-spacing:1px;color:#1e2bfa}.eyebrow{position:absolute;right:110px;top:94px;font-size:24px;color:#6b6b6b}
.rule{height:4px;width:100%;background:#1e2bfa;margin-top:28px;transform-origin:left}
.title{font-size:86px;font-weight:750;letter-spacing:-3px;line-height:1.25;margin:64px 0 30px}.blue{color:#1e2bfa}.body{font-size:32px;color:#6b6b6b;line-height:1.7;margin:0}
.note{position:absolute;left:110px;bottom:96px;font-size:26px;color:#6b6b6b}.footer{position:absolute;right:110px;bottom:96px;font-size:25px;color:#1e2bfa}.meter{position:absolute;left:110px;right:110px;bottom:64px;height:5px;background:rgba(30,43,250,.15)}.fill{height:100%;background:#1e2bfa;width:100%;transform-origin:left}
.card{border:2px solid rgba(30,43,250,.2);background:rgba(30,43,250,.04);border-radius:14px;padding:28px}.badge{display:inline-block;background:rgba(30,43,250,.08);color:#1e2bfa;border-radius:100px;padding:12px 25px;font-size:26px;font-weight:600}
.promise{position:absolute;right:110px;top:320px;width:560px}.promise .card{margin-bottom:26px;font-size:38px}.promise small{display:block;color:#6b6b6b;font-size:25px;margin-top:12px}
.values{display:flex;gap:22px;margin-top:55px}.big{font-size:104px;line-height:1.18;font-weight:750;margin:35px 0}.roles{position:absolute;left:905px;top:260px;width:900px;height:510px}.lead{position:absolute;left:228px;top:0;width:380px;text-align:center;font-size:34px}.role{position:absolute;width:260px;font-size:31px;text-align:center}.role small{display:block;font-size:23px;color:#6b6b6b;margin-top:10px}.r1{left:0;top:160px}.r2{left:290px;top:160px}.r3{left:580px;top:160px}.r4{left:145px;top:345px}.r5{left:435px;top:345px}.diagram{position:absolute;inset:0;width:900px;height:510px;pointer-events:none}.diagram path{fill:none;stroke:#1e2bfa;stroke-width:3;stroke-dasharray:700;stroke-dashoffset:700}
.board{display:grid;grid-template-columns:repeat(4,1fr);gap:25px;margin-top:40px}.column{height:390px;border-top:4px solid #1e2bfa;background:rgba(30,43,250,.04);padding:25px;border-radius:0 0 14px 14px}.coltitle{font-size:29px;font-weight:650;margin:0 0 25px}.task{padding:22px;background:#fdfae7;border:2px solid rgba(30,43,250,.2);border-radius:12px;margin-bottom:18px;font-size:28px;line-height:1.5}.task small{font-size:23px;color:#6b6b6b;display:block;margin-top:10px}.boardtitle{font-size:74px;margin:40px 0 0}
.proof{position:absolute;left:980px;top:260px;width:815px;padding:36px}.checkrow{display:flex;align-items:center;gap:24px;font-size:29px;padding:24px 0;border-bottom:1px solid rgba(30,43,250,.2)}.checkrow:last-child{border:0}.mark{width:42px;height:42px;display:grid;place-items:center;color:#1e2bfa;border:2px solid #1e2bfa;border-radius:50%;font-size:26px}.rowlabel{flex:1}.result{font-size:25px;color:#1e2bfa}.pending{color:#6b6b6b}.code{font-size:36px;font-weight:650;letter-spacing:1px}.onboard{display:grid;grid-template-columns:1fr 1fr;gap:32px;margin-top:40px}.onboard .card{padding:34px}.onboard p{font-size:26px;color:#6b6b6b;margin:18px 0 0}.closing{font-size:37px;color:#1e2bfa;margin-top:42px}
`;
const scenes = [
{id:'01-promise',content:`<h1 class="title reveal" data-at="0.4">一句需求，<p class="blue" style="margin:16px 0 0">成为团队的共同目标。</p></h1><p class="body reveal" data-at="2.1">从角色分工，到审查返工。</p><p class="big blue reveal" data-at="4.3">交付有据可查。</p><div class="values reveal" data-at="5.8"><span class="badge">原生协作</span><span class="badge">可追踪</span><span class="badge">可验收</span></div><div class="promise"><div class="card reveal" data-at="1.4">01 / 明确目标<small>范围与验收</small></div><div class="card reveal" data-at="3">02 / 团队协作<small>按需角色与 Skills</small></div><div class="card reveal" data-at="5">03 / 汇总交付<small>文件、验证与证据</small></div></div>`,note:'从需求到交付，一条清晰的工程路径',footer:'01 / PROMISE'},
{id:'02-team',content:`<h1 class="title reveal" data-at="0.4">让专业角色，<p class="blue" style="margin:15px 0 0">各司其职。</p></h1><p class="body reveal" data-at="2.4">宿主原生工具负责协作与执行。</p><div class="values reveal" data-at="5.9"><span class="badge">按需组队</span><span class="badge">Skills 随任务使用</span></div><div class="roles"><svg class="diagram" viewBox="0 0 900 510" data-layout-ignore><path d="M418 115V135H130V160 M418 135V160 M418 135H710V160 M418 135H870V318H275V345 M565 318V345"/></svg><div class="card lead reveal" data-at="1">Coordinator / 协调</div><div class="card role r1 reveal" data-at="2.2">需求<small>明确验收</small></div><div class="card role r2 reveal" data-at="3">架构<small>界定边界</small></div><div class="card role r3 reveal" data-at="3.8">开发<small>实施与验证</small></div><div class="card role r4 reveal" data-at="4.6">审查<small>独立复核</small></div><div class="card role r5 reveal" data-at="5.4">设计 UE<small>视觉依据</small></div></div>`,note:'演示数据 · 角色职责示意；实际按任务选择角色',footer:'02 / TEAM'},
{id:'03-board',content:`<h1 class="title boardtitle reveal" data-at="0.4">谁在做，<span class="blue">做到哪。</span></h1><p class="body reveal" data-at="1.3">工单与执行独立追踪，关联关系保留在详情中。</p><div class="board"><div class="column reveal" data-at="1.8"><p class="coltitle">待开始</p><div class="task reveal" data-at="2.4">#01 搜索功能<small>父工单 · 范围已明确</small></div></div><div class="column reveal" data-at="2.2"><p class="coltitle">进行中</p><div class="task reveal" data-at="3.1">搜索行为实现<small>Developer · 归属 #01</small></div></div><div class="column reveal" data-at="2.6"><p class="coltitle">待评审</p><div class="task reveal" data-at="4.5">搜索结果复核<small>Reviewer · 归属 #01</small></div></div><div class="column reveal" data-at="3"><p class="coltitle">已完成</p><div class="task reveal" data-at="5.5">需求边界分析<small>Requirements · 执行完成</small></div></div></div><div class="values reveal" data-at="6.3"><span class="badge">Kanban</span><span class="badge">Org Chart</span><span class="badge">任务详情</span></div>`,note:'演示数据 · 功能示意；只读展示，协作在原生对话中完成',footer:'03 / VISIBILITY'},
{id:'04-proof',content:`<h1 class="title reveal" data-at="0.4">完成，<p class="blue" style="margin:15px 0 0">有依据。</p></h1><p class="body reveal" data-at="2.2">具体验收条件，具体文件与验证。</p><div class="values reveal" data-at="5.8"><span class="badge">执行结束 ≠ 验收完成</span></div><div class="card proof reveal" data-at="1.3"><div class="brand">交付证据 / #01</div><div class="checkrow reveal" data-at="2.3"><span class="mark">1</span><span class="rowlabel">具体 AC</span><span class="result">有核对方法</span></div><div class="checkrow reveal" data-at="3.3"><span class="mark">2</span><span class="rowlabel">Agent 自验证</span><span class="result">文件 + 结果</span></div><div class="checkrow reveal" data-at="4.3"><span class="mark">3</span><span class="rowlabel">独立审查</span><span class="result">审查与复查</span></div><div class="checkrow reveal" data-at="5.3"><span class="mark">4</span><span class="rowlabel">适用的人工核验</span><span class="result pending">待确认</span></div></div>`,note:'演示数据 · 证据结构示意；适用的人工核验独立记录',footer:'04 / EVIDENCE'},
{id:'05-start',content:`<h1 class="title reveal" data-at="0.4" style="font-size:100px">Codex <span class="blue">Agent Team</span></h1><p class="body reveal" data-at="1.5">原生团队协作 · 只读进度追踪 · 有据可查的交付</p><div class="onboard"><div class="card reveal" data-at="2.7"><span class="badge">首次准备目标工程</span><p class="code" style="color:#111111">$setup-agent-team</p><p>显式安装所需团队技能依赖</p></div><div class="card reveal" data-at="4"><span class="badge">日常启用团队流程</span><p class="code" style="color:#111111">@Agent Team</p><p>在原生对话中给出目标与验收</p></div></div><p class="closing reveal" data-at="5.6">从一句需求，开始团队协作。</p>`,note:'Codex 插件 / 独立 Web · 接入能力以目标客户端实测为准',footer:'05 / GET STARTED'}
];
mkdirSync('compositions/frames',{recursive:true});
for(const [i,scene] of scenes.entries()) {
  const id=scene.id;
  const html=`<template><style>${css.replaceAll('.stage',`.${id}`).replaceAll('assets/noto','assets/noto')}</style><div id="root" data-composition-id="${id}" data-width="1920" data-height="1080" data-duration="9"><div id="scene-${id}-bg" class="clip ground" data-start="0" data-duration="9" data-track-index="0"></div><section id="scene-${id}-sheet" class="clip sheet" data-start="0" data-duration="9" data-track-index="1"><div class="brand">CODEX AGENT TEAM</div><div class="eyebrow">NATIVE COLLABORATION / READ-ONLY VIEW</div><div class="rule"></div>${scene.content}<div class="note">${scene.note}</div><div class="footer">${scene.footer}</div><div class="meter"><div class="fill"></div></div></section></div><script>{const scope=document.querySelector('[data-composition-id="${id}"]');const tl=gsap.timeline({paused:true});tl.fromTo(scope.querySelector('.rule'),{scaleX:0},{scaleX:1,duration:1,ease:'power3.out'},0);for(const el of scope.querySelectorAll('.reveal')){tl.fromTo(el,{opacity:0,y:24},{opacity:1,y:0,duration:0.75,ease:'power3.out'},Number(el.dataset.at));}tl.fromTo(scope.querySelector('.fill'),{scaleX:0},{scaleX:1,duration:9,ease:'none'},0);const path=scope.querySelector('.diagram path');if(path)tl.to(path,{strokeDashoffset:0,duration:4.5,ease:'power2.out'},1.4);window.__timelines['${id}']=tl;}</script></template>`;
  writeFileSync(`compositions/frames/${scene.id}.html`,html);
}
const storyboard=readFileSync('STORYBOARD.md','utf8').replaceAll('- status: outline','- status: animated');
writeFileSync('STORYBOARD.md',storyboard);
console.log('Built 5 scenes, 45s, silent, demo labels included.');
